<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_Name</name>
   <tag></tag>
   <elementGuidId>e2f83499-af13-4513-a8be-1c90db026bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00dfddb6-3571-41e0-8997-950b096dbd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-input-element cdk-text-field-autofill-monitored</value>
      <webElementGuid>f8e2d061-84a3-4f43-b48f-bbf51e8840e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b5560b8-50f9-4a3e-adbb-96a05284c911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a779a853-d385-4293-97fb-a6a0b943077a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>7570cd95-2159-42b4-b917-d579ce1e4f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>4af3fa70-dc4a-4676-873b-97d1478b60cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>679bf0ba-2640-4a97-af10-bd48782ca3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4557d335-030d-4465-8c72-5926f4f663ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Name&quot;)</value>
      <webElementGuid>530c8155-c36e-4e9a-9fa9-26fc36390871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Name']</value>
      <webElementGuid>0d37dbc1-67f7-4487-8d81-6bf110897e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-0']/div/div/ng-component/form/mat-dialog-content/iov-input/div/iov-form-input/div/input</value>
      <webElementGuid>56707f91-da3c-4960-a3f4-c517c7eff74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iov-input/div/iov-form-input/div/input</value>
      <webElementGuid>7c342ac2-8142-41cf-919b-1a5085aefdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Name' and @id = 'Name']</value>
      <webElementGuid>997b4908-23dc-414e-8204-b8a27bc5c5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
