<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-hint_This field is mandatory</name>
   <tag></tag>
   <elementGuidId>5e92f81a-a947-42b5-acc6-40817fe68d21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-hint-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-hint[@id='mat-mdc-hint-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;This field is mandatory.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-hint</value>
      <webElementGuid>8ee87d9a-bafe-404a-b9bb-bdcc0fd8e67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-hint mat-mdc-form-field-bottom-align hint-error ng-star-inserted</value>
      <webElementGuid>741081ca-1102-4043-92b3-394f0a43203b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-hint-3</value>
      <webElementGuid>46a7f431-299c-46c1-9219-3e47a24c5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is mandatory.</value>
      <webElementGuid>63287296-c7d5-4934-9260-c258ccd7d4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-hint-3&quot;)</value>
      <webElementGuid>c3ba8775-0e0a-4ca6-9b67-cdb14d89d144</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-hint[@id='mat-mdc-hint-3']</value>
      <webElementGuid>d3f2dca0-9a44-4025-b0af-de78eaaf56e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::mat-hint[1]</value>
      <webElementGuid>53d79616-4337-4e7c-9550-5f98d95a5d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::mat-hint[1]</value>
      <webElementGuid>a1c66943-feb5-40e2-aa5d-6b2249abb3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::mat-hint[1]</value>
      <webElementGuid>80df617f-0ce5-45b9-b905-457ddf4f358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='optional'])[1]/preceding::mat-hint[1]</value>
      <webElementGuid>96d68532-c141-46e0-91a5-f41addb0f4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This field is mandatory.']/parent::*</value>
      <webElementGuid>dc939ecb-d4b3-4119-ad78-a5a055e701c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-hint</value>
      <webElementGuid>239c1a15-1cd8-4ac1-854c-f4a7b6ec861d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-hint[@id = 'mat-mdc-hint-3' and (text() = 'This field is mandatory.' or . = 'This field is mandatory.')]</value>
      <webElementGuid>ab0ff691-f0c2-4afe-ada0-db73be8a9ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
