<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_close</name>
   <tag></tag>
   <elementGuidId>6a49b976-50e0-4226-8c61-b5ba256f0f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mdc-button__label > mat-icon.mat-icon.notranslate.material-symbols-outlined.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='mdc-button__label']/mat-icon[text()='close'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>foreignobject >> internal:has-text=&quot;close7u76uefefsefeEditedAutomationOrgWood United Kingdom 1 2&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>6aad11b8-e253-42ad-afc6-cab21c3638ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>660a97d3-7570-4462-a359-c9a82c7fb73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-symbols-outlined mat-icon-no-color</value>
      <webElementGuid>a2126388-5d15-4b2e-a3d9-9819923e2af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34115e60-474e-4d70-a8c8-bc54ed0abc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>4b414b32-7d09-4535-93ec-14abe9f4c847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>66ab6bd1-3408-46a0-838c-a6d55ed1c836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;node-svg&quot;)/g[@class=&quot;flow-chart-content&quot;]/g[@class=&quot;output&quot;]/g[@class=&quot;nodes&quot;]/g[@class=&quot;node&quot;]/g[@class=&quot;label&quot;]/g[1]/foreignobject[1]/div[1]/div[@class=&quot;flow-chart-node&quot;]/div[1]/iov-button[@class=&quot;clickable remove-button&quot;]/button[@class=&quot;mdc-button mdc-button--unelevated mat-mdc-unelevated-button iov-filled-button icon medium primary clickable mat-primary mat-mdc-button-base&quot;]/span[@class=&quot;mdc-button__label&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-symbols-outlined mat-icon-no-color&quot;]</value>
      <webElementGuid>521b9f40-6743-4690-aef8-13ab24f23f7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop locations here'])[1]/following::mat-icon[1]</value>
      <webElementGuid>3e753efa-3dd0-4663-a967-dc9d72342933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='efefsefe'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>06267e35-6247-499d-b45a-edd7341445d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EditedAutomationOrg'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>d2e663e5-82cf-4ba3-9112-342faa189b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='close']/parent::*</value>
      <webElementGuid>44d0ccb5-83cd-4be0-a0d1-cc601c44493a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/mat-icon</value>
      <webElementGuid>cf5fdc17-44c2-42fd-99c9-614e70320df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'close' or . = 'close')]</value>
      <webElementGuid>cddf3085-208d-4d36-aa5e-3117ecadc8a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
