<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_m3</name>
   <tag></tag>
   <elementGuidId>a7eda8b9-0cec-4244-83bb-2fdfac6eca0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iov-input.ng-touched.ng-dirty.ng-valid > div.form-field-item.ng-star-inserted > iov-form-input > div.input-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Initial quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^m3$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>850fdb65-0d2a-45a5-9d43-b456c548830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-container</value>
      <webElementGuid>170f495a-53cc-444f-abed-534fd7d9b11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>m3</value>
      <webElementGuid>7c6340d9-f90f-48fa-9540-7999f1c45821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-dialog-2&quot;)/div[@class=&quot;mat-mdc-dialog-inner-container mdc-dialog__container&quot;]/div[@class=&quot;mat-mdc-dialog-surface mdc-dialog__surface&quot;]/ng-component[@class=&quot;mat-mdc-dialog-component-host ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/mat-dialog-content[@class=&quot;mat-mdc-dialog-content mdc-dialog__content ng-star-inserted&quot;]/div[@class=&quot;row-container&quot;]/div[@class=&quot;row row-2&quot;]/div[@class=&quot;item&quot;]/iov-input[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;form-field-item ng-star-inserted&quot;]/iov-form-input[1]/div[@class=&quot;input-container&quot;]</value>
      <webElementGuid>4fd0cca7-0879-43fa-abcb-15aee55ead95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-mdc-dialog-2']/div/div/ng-component/form/mat-dialog-content/div/div/div[5]/iov-input/div/iov-form-input/div</value>
      <webElementGuid>1ce9a928-e108-43df-9c1d-3b619ed95037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial quantity'])[1]/following::div[1]</value>
      <webElementGuid>7fe7e5ca-6a8d-4b61-a4b0-d158bc6e4962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit of measurement'])[1]/following::div[6]</value>
      <webElementGuid>a2597701-cc90-4362-bb0c-6f0ae1c05410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created at location'])[1]/preceding::div[1]</value>
      <webElementGuid>81561ba8-ade0-4c2f-a0a7-bd120cc77514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/iov-input/div/iov-form-input/div</value>
      <webElementGuid>0e4d5fb7-828b-45c6-8344-71cfbd1bf89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'm3' or . = 'm3')]</value>
      <webElementGuid>ce4a5f3a-b464-4423-aadb-ffe4dc738777</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
