<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Zack Crawley</name>
   <tag></tag>
   <elementGuidId>4f9b2d84-2727-41ed-a79b-c0d654a70309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-option[@role='option'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-55</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Zack Crawley&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>dd6d5c3a-5de6-473f-a773-5911161ed9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>421b534f-c687-4a64-b3f0-bf56e61ffab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-option mdc-list-item ng-tns-c3964489799-33 ng-star-inserted</value>
      <webElementGuid>1e7cb798-e283-4003-8e09-56cdaeaf11f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-55</value>
      <webElementGuid>2c9892b0-80e3-4caf-8c04-baf169488699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d65a8308-56b6-42a3-b5f6-348516d2beb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef127541-740c-4b46-a23e-597dd83b2be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Zack Crawley </value>
      <webElementGuid>68d296b9-6c44-442d-818c-721086053ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-55&quot;)</value>
      <webElementGuid>976f7397-81dc-49d1-84b6-47eaba620fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-55']</value>
      <webElementGuid>c77f506a-74f5-4405-a602-bcd948c9f725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-19']/mat-option[5]</value>
      <webElementGuid>699b796b-9939-4cc5-b0a4-4732c89d669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Symonds'])[6]/following::mat-option[1]</value>
      <webElementGuid>027cc3d4-ac9c-4c15-b1db-2bce9c1476cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noman Digest'])[6]/following::mat-option[2]</value>
      <webElementGuid>35d560ff-461a-4ba2-ad78-4aa2f35e89c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QAAutomationLocation'])[2]/preceding::mat-option[1]</value>
      <webElementGuid>0e4b4d22-b845-4e5b-af5b-38f693b51f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]</value>
      <webElementGuid>f8fcbdff-e1cc-4b41-bf11-fed6daa67d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-55' and (text() = ' Zack Crawley ' or . = ' Zack Crawley ')]</value>
      <webElementGuid>afab7b62-a196-4848-a1c3-1dae67bf79e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
