<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_QAAutomationLocation</name>
   <tag></tag>
   <elementGuidId>155aed2f-8860-4e12-8fdc-34641d3eb562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-option[@role='option'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-91</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;QAAutomationLocation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>4f1fe7d0-32f5-4ab7-9c4c-e0359593ed3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>de2ab8b3-07b1-4c47-ba35-1f5bb85466bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-option mdc-list-item ng-tns-c3964489799-44 ng-star-inserted mdc-list-item--selected</value>
      <webElementGuid>dc6584e4-6dde-473d-b91c-09628f1466b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-91</value>
      <webElementGuid>4cc07b95-6f64-47ee-9b19-446798cee6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8255f9ed-81b7-4942-9f39-6782fd3825f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce95acdc-5e03-41d1-b69d-b31b4ca358b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> QAAutomationLocation </value>
      <webElementGuid>d17d334e-f58c-422d-afcb-fb5af66130f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-91&quot;)</value>
      <webElementGuid>4bc88e6e-efe2-42b3-9e4e-314331a4193d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-91']</value>
      <webElementGuid>8d811966-198f-409f-90fc-fbdb7639f7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-30']/mat-option[6]</value>
      <webElementGuid>33cc9041-9bb3-4ecc-993e-8a29c3949866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Crawley'])[3]/following::mat-option[1]</value>
      <webElementGuid>26a685b7-12e0-4f6e-8aa1-810427fddeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Symonds'])[6]/following::mat-option[2]</value>
      <webElementGuid>09817383-1e00-4ffd-82f3-30e06e194add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wood'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>bb6b1018-f748-408a-8c48-4ff294c8ff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]</value>
      <webElementGuid>f48b9977-e570-49a5-b2a5-1c55c72da653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-91' and (text() = ' QAAutomationLocation ' or . = ' QAAutomationLocation ')]</value>
      <webElementGuid>58e75c9c-f3e8-443a-a42c-8fc648183302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
