<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_QAAutomationLocation</name>
   <tag></tag>
   <elementGuidId>98bca79d-0238-44ff-9b3d-97a0499ac68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-65 > span.mdc-list-item__primary-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-65']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;QAAutomationLocation&quot;i] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4cd5f50-5d94-4536-8f06-3eb5551e1af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__primary-text</value>
      <webElementGuid>d718ca57-611b-46a5-9e04-6c089e82c063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> QAAutomationLocation </value>
      <webElementGuid>d207ed84-9e92-4d88-9b14-30e10c578c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-65&quot;)/span[@class=&quot;mdc-list-item__primary-text&quot;]</value>
      <webElementGuid>bdc6ee70-d4ba-4dfb-969d-f92fd247a2cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-65']/span</value>
      <webElementGuid>e6656b9a-581f-40ca-8310-7e32d0da0712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Crawley'])[3]/following::span[1]</value>
      <webElementGuid>ee33c70c-bb0e-463a-8992-c80bb1dc1829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ben Symonds'])[6]/following::span[2]</value>
      <webElementGuid>11ca259f-15e4-4dd7-af0b-91890031287d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wood'])[1]/preceding::span[1]</value>
      <webElementGuid>e6a7123a-6056-4eac-920d-121577ee308f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loll'])[1]/preceding::span[2]</value>
      <webElementGuid>04b8fe81-942f-4afa-9169-9bd3f8c153b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]/span</value>
      <webElementGuid>9e88f2dc-60c8-409f-86c8-7c084b4b3dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' QAAutomationLocation ' or . = ' QAAutomationLocation ')]</value>
      <webElementGuid>dd3b194a-18b0-4eae-92f8-8b3bcb3666af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
