<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_cancel</name>
   <tag></tag>
   <elementGuidId>3ebfd4d3-69d8-4bdd-b54b-4496ec6804d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.suffix-icon.clear-icon.material-symbols-outlined.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-2']/div/div/div/div[4]/iov-input-select/div/div/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;cancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d3c4cda3-3806-45a8-8477-d77bed7f70f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>58531144-f2bc-41ee-8448-92338add8077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tp</name>
      <type>Main</type>
      <value>Clear value</value>
      <webElementGuid>eeb565c0-0dc8-48fb-b68f-0e1e7422cf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate suffix-icon clear-icon material-symbols-outlined mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>7966dba3-b720-4ba3-a844-e63b76f088c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c1cd4fd-0953-4038-a999-1dd118270ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>9399f0b3-a979-427d-a74f-66d883a499a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> cancel </value>
      <webElementGuid>c4892118-4cfb-4ca9-a0ea-bf037553ba9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-2&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c857250080-18&quot;]/div[@class=&quot;row-container ng-tns-c857250080-18 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;row row-2&quot;]/div[@class=&quot;item&quot;]/iov-input-select[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-field-item ng-star-inserted&quot;]/div[@class=&quot;input-container&quot;]/mat-icon[@class=&quot;mat-icon notranslate suffix-icon clear-icon material-symbols-outlined mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>314808ce-e302-4274-bcbd-cdf6384769cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-2']/div/div/div/div[4]/iov-input-select/div/div/mat-icon</value>
      <webElementGuid>e8533b9c-2a8c-4966-9eb3-39f4b1a4a98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::mat-icon[1]</value>
      <webElementGuid>a1218cd0-12db-453e-9a8c-747cd393449e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='optional'])[4]/following::mat-icon[1]</value>
      <webElementGuid>a22dc172-557b-4e74-97f7-979653a46b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>d399774e-c7d3-4a9d-bf8a-5e33fd68ab95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cancel']/parent::*</value>
      <webElementGuid>a097c3f5-8422-46e6-807d-f9db5a3e9d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iov-input-select/div/div/mat-icon</value>
      <webElementGuid>9ac1d1d2-8037-42c6-8aa7-fb0124cd345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' cancel ' or . = ' cancel ')]</value>
      <webElementGuid>a6d061f4-ccc6-42fb-90d6-98c28630a809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
