<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Same address as organisation address</name>
   <tag></tag>
   <elementGuidId>57138c53-b3cd-4695-9209-f658f1a7cf5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-mdc-checkbox-1']/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Same address as organisation address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6612081a-ef7a-4578-8c59-c6b2caf07099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c298fdef-1ce6-41e5-836d-21d638ca4c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Same address as organisation address </value>
      <webElementGuid>f8211784-203e-4718-83f2-ea4add0ff3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-checkbox-1&quot;)/div[@class=&quot;mdc-form-field mat-internal-form-field&quot;]/label[@class=&quot;mdc-label&quot;]/div[@class=&quot;label&quot;]</value>
      <webElementGuid>13036165-a609-4a86-85fc-6ed4fa3443f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-mdc-checkbox-1']/div/label/div</value>
      <webElementGuid>326c32b2-ccf5-410b-bbd8-75e991625d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QAAutomation'])[1]/following::div[8]</value>
      <webElementGuid>afdd2913-2e57-4104-877a-6ef2da47f128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select from the list or type it in and hit enter to add a new type'])[1]/following::div[9]</value>
      <webElementGuid>5f7d91fe-d865-4b42-8a7d-bafcb7f159e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[2]/preceding::div[1]</value>
      <webElementGuid>5e9124b3-f105-4c2e-83a9-dc5dfb4f63a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='optional'])[1]/preceding::div[4]</value>
      <webElementGuid>2be29103-6455-4e46-8e76-b233dbef6131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Same address as organisation address']/parent::*</value>
      <webElementGuid>7cebbcdf-bef6-436f-aefa-380849e1fa1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>f24a5dd3-bf2a-4e29-9f02-d84baf148d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Same address as organisation address ' or . = ' Same address as organisation address ')]</value>
      <webElementGuid>c9d46ff8-9d46-4401-8f95-fda1a2afe36e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
