<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New organisation</name>
   <tag></tag>
   <elementGuidId>057a445f-d2ad-4442-a926-084de6c0614c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-accordion-child-0']/div/div/div/div[2]/iov-button/button/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New organisation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2535f841-f1ea-4580-a028-24254dba773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>e1178d28-5a1c-482b-bdb7-ffe8ba765323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New organisation</value>
      <webElementGuid>6fae8a88-dce1-4b1e-9e8c-ec9813e1382c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-0&quot;)/div[@class=&quot;mat-expansion-panel-body ng-tns-c857250080-7&quot;]/div[@class=&quot;row-container ng-tns-c857250080-7 ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row row-2&quot;]/div[@class=&quot;item new-organisation-link&quot;]/iov-button[@class=&quot;no-border content-underline&quot;]/button[@class=&quot;mdc-button mdc-button--unelevated mat-mdc-unelevated-button iov-filled-button ghost default primary no-border content-underline mat-primary mat-mdc-button-base ng-star-inserted cdk-focused cdk-keyboard-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/span[@class=&quot;underline&quot;]</value>
      <webElementGuid>711e186c-fb55-4dc1-aab0-eb742370d21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-0']/div/div/div/div[2]/iov-button/button/span[2]/span</value>
      <webElementGuid>9c93fbc7-def6-4aa3-a9b1-344d3dced7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/following::span[3]</value>
      <webElementGuid>72d96752-0e05-4a37-9527-b4abf78d4dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation details'])[1]/following::span[4]</value>
      <webElementGuid>00a28158-d596-4b4f-afa9-81a2b8ce5d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location details'])[1]/preceding::span[4]</value>
      <webElementGuid>31251f20-ae1b-463c-bed9-56bcbdf76fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::span[6]</value>
      <webElementGuid>01e8cedd-94bb-4d96-a1ee-2c65e888f181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New organisation']/parent::*</value>
      <webElementGuid>a772a3d1-ad59-4b53-b241-83dc6a41bb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>c1112a77-adc6-49dc-ad16-28a073c9d57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' New organisation' or . = ' New organisation')]</value>
      <webElementGuid>7c816985-a3fe-4bad-95a7-09181b1bc289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
