<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AutomatedQACertificate</name>
   <tag></tag>
   <elementGuidId>9e451f35-a741-4c1e-b2fb-8635e7abe9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Source'])[2]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-certificate-list-items >> internal:text=&quot;AutomatedQACertificate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>339818d7-ea53-4b71-bc10-ec8c6c86aa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tpplacement</name>
      <type>Main</type>
      <value>top-start</value>
      <webElementGuid>06d3d52d-df6b-4789-a6b0-2ce756fef50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>401d7d03-700d-401c-bf44-6b485582fde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AutomatedQACertificate </value>
      <webElementGuid>1ccd3ba5-363b-4495-8a9a-018b08ee8ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;app-container&quot;]/div[@class=&quot;ng-star-inserted&quot;]/iov-sidebar-menu[1]/div[@class=&quot;main-container ng-star-inserted menu-collapsed&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content sidenav-content-with-collapsed-menu&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-page-container&quot;]/div[@class=&quot;element-content&quot;]/iov-tab-set[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;tab-content&quot;]/iov-tab[2]/app-attachments[@class=&quot;ng-tns-c1757308655-21 ng-star-inserted&quot;]/div[@class=&quot;right-side-panel-container ng-tns-c1757308655-21&quot;]/div[@class=&quot;content ng-tns-c1757308655-21&quot;]/app-certificate-list-items[@class=&quot;ng-tns-c1757308655-21 ng-star-inserted&quot;]/div[@class=&quot;full-width-items-container ng-star-inserted&quot;]/div[@class=&quot;item hover-visibility-container ng-star-inserted&quot;]/iov-certificate-content-card[1]/div[@class=&quot;container-flex-space-between&quot;]/div[@class=&quot;left-content&quot;]/div[@class=&quot;number&quot;]</value>
      <webElementGuid>6b78d921-3e2f-46a1-9d20-93abd0e51276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Source'])[2]/following::div[1]</value>
      <webElementGuid>b982637e-259f-49b6-9b0d-c32310126d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validity: Aug 23, 2024 -'])[1]/following::div[6]</value>
      <webElementGuid>ff3e3cc0-ff0d-457f-90d2-82a6794f919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validity: Aug 27, 2060 -'])[1]/preceding::div[1]</value>
      <webElementGuid>edd347d0-9c9d-445b-a41a-fa545d4a28cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add certificates'])[1]/preceding::div[3]</value>
      <webElementGuid>12f8b8cb-f577-409f-9dcf-baa6a7ade86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AutomatedQACertificate']/parent::*</value>
      <webElementGuid>4138784f-f252-45ea-aae2-a9a651280ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iov-certificate-content-card/div/div/div[2]</value>
      <webElementGuid>c3561d02-9b29-4293-90d3-16340e2cc89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' AutomatedQACertificate ' or . = ' AutomatedQACertificate ')]</value>
      <webElementGuid>d5872118-34af-4fc9-b5c1-59de81c5393b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
