<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_add</name>
   <tag></tag>
   <elementGuidId>83a09d25-3fcf-44d5-b2e3-f64ba61c4d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mdc-button.mdc-button--unelevated.mat-mdc-unelevated-button.iov-filled-button.icon.medium.primary.mat-primary.mat-mdc-button-base.ng-star-inserted.cdk-focused.cdk-keyboard-focused > span.mdc-button__label > mat-icon.mat-icon.notranslate.material-symbols-outlined.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='mdc-button__label']/mat-icon[text()='add'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iov-material-card-content >> internal:has-text=&quot;sdvsv frfeef add&quot;i >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d42ec786-3c49-4720-825d-f7097e52c72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a049d3e-e47f-403f-bc4c-425a8d4d969e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-symbols-outlined mat-icon-no-color</value>
      <webElementGuid>d5974c51-bea7-40df-831b-e1179217eff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fb0e1fb-6b0c-4d0f-a040-c26caa340b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>a39f5b35-1bba-40c3-a549-6520d7e9c683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>fc2678b2-a59f-4e53-861f-c9c55782db25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-5&quot;)/iov-draggable-card[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cdk-drag main-container ng-star-inserted&quot;]/iov-material-card-content[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-flex-space-between&quot;]/iov-button-group[1]/div[@class=&quot;buttons ng-star-inserted&quot;]/iov-button[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;mdc-button mdc-button--unelevated mat-mdc-unelevated-button iov-filled-button icon medium primary mat-primary mat-mdc-button-base ng-star-inserted cdk-focused cdk-keyboard-focused&quot;]/span[@class=&quot;mdc-button__label&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-symbols-outlined mat-icon-no-color&quot;]</value>
      <webElementGuid>cd6db4da-9697-4bf3-b5eb-166c6e987cf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-drop-list-5']/iov-draggable-card/div/iov-material-card-content/div/iov-button-group/div/iov-button/button/span[2]/mat-icon</value>
      <webElementGuid>a8d42fdb-9f20-40dc-8afc-5f23c669965b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='frfeef'])[1]/following::mat-icon[1]</value>
      <webElementGuid>6aa99c56-053e-43ac-8e72-94d26fc59f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sdvsv'])[1]/following::mat-icon[1]</value>
      <webElementGuid>372547ac-12f7-4e5a-ab8d-65382f3473ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rferger'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>6100253e-9496-4c2a-b867-0af98ce99d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rgrgr'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>619231f6-eed0-4d4a-b4c6-fc555925a4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iov-material-card-content/div/iov-button-group/div/iov-button/button/span[2]/mat-icon</value>
      <webElementGuid>ee93da57-d21d-4773-9b91-048bda2cb73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'add' or . = 'add')]</value>
      <webElementGuid>9d6ddc4a-6443-4484-9fe6-1bd6715a997a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
